Missing nuget packages for integration projects (#62)
* current progress

* Move test project to solution and create

Directory.Build.props files to simplify the configuration process

* Set up CI with Azure Pipelines

[skip ci]

* Remove redundant PackageId from

Directory.Build.props

* Fix LangVersion property

* Fix unit test project missing source project

references

* Update test project path

* Update azure-pipelines.yml for Azure Pipelines

* Remove duplicate tasks

* Update azure-pipelines.yml for Azure Pipelines

* Update azure-pipelines.yml for Azure Pipelines

* Update azure-pipelines.yml for Azure Pipelines

* Remove Benchmarks from pack process by ading

<GeneratePackageOnBuild>false</GeneratePackageOnBuild>

* Make protram and main method public to avoid

error CS5001 on azure pipelines

* Update azure-pipelines.yml for Azure Pipelines

* Update azure-pipelines.yml for Azure Pipelines

* Update azure-pipelines.yml for Azure Pipelines

* Update azure-pipelines.yml for Azure Pipelines

* Update azure-pipelines.yml for Azure Pipelines

* Update azure-pipelines.yml for Azure Pipelines

* Update azure-pipelines.yml for Azure Pipelines

* Reorder project structure

-Bring solution to the root path
-Create benchmarks folder and move project
-Move test projects from src/test to test
-Reorder projects inside solutions
-Craete Directory.Build.props for tests projects and propagate code
coverage and commons nuget packages.
-Update azure .ylm pipeline to produce code coverage diagrams and result

* Fix solution items

Co-authored-by: Steve Smith <steve@kentsmiths.com>
Co-authored-by: Daniel Meza <dmeza@speedsol.com>