Smart flag enum (#160)
* Added SmartFlagEnum Functionality

* Added AutoFixture Support for SmarFlagEnum Type

* SmartFlagEnum 1.0. Serialization and AutoFixture Utilities and UnitTests Complete.

* Return all flags for underlying type MaxValue

When FromValue() is called on a SmartFlagEnum with the corresponding MaxValue of the base tyoe as the value agrument, a list of all defined enum values is returned. This is similar to passing negative one.

* Pulled In Upstream Changes and Resolved Conflicts, Files Moved To New Folder Structure

* Missing nuget packages for integration projects (#62)

* current progress

* Move test project to solution and create

Directory.Build.props files to simplify the configuration process

* Set up CI with Azure Pipelines

[skip ci]

* Remove redundant PackageId from

Directory.Build.props

* Fix LangVersion property

* Fix unit test project missing source project

references

* Update test project path

* Update azure-pipelines.yml for Azure Pipelines

* Remove duplicate tasks

* Update azure-pipelines.yml for Azure Pipelines

* Update azure-pipelines.yml for Azure Pipelines

* Update azure-pipelines.yml for Azure Pipelines

* Remove Benchmarks from pack process by ading

<GeneratePackageOnBuild>false</GeneratePackageOnBuild>

* Make protram and main method public to avoid

error CS5001 on azure pipelines

* Update azure-pipelines.yml for Azure Pipelines

* Update azure-pipelines.yml for Azure Pipelines

* Update azure-pipelines.yml for Azure Pipelines

* Update azure-pipelines.yml for Azure Pipelines

* Update azure-pipelines.yml for Azure Pipelines

* Update azure-pipelines.yml for Azure Pipelines

* Update azure-pipelines.yml for Azure Pipelines

* Reorder project structure

-Bring solution to the root path
-Create benchmarks folder and move project
-Move test projects from src/test to test
-Reorder projects inside solutions
-Craete Directory.Build.props for tests projects and propagate code
coverage and commons nuget packages.
-Update azure .ylm pipeline to produce code coverage diagrams and result

* Fix solution items

Co-authored-by: Steve Smith <steve@kentsmiths.com>
Co-authored-by: Daniel Meza <dmeza@speedsol.com>

* Bump MessagePack from 1.7.3.4 to 1.9.11 in /src/SmartEnum.MessagePack (#68)

Bumps [MessagePack](https://github.com/neuecc/MessagePack-CSharp) from 1.7.3.4 to 1.9.11.
- [Release notes](https://github.com/neuecc/MessagePack-CSharp/releases)
- [Commits](https://github.com/neuecc/MessagePack-CSharp/compare/v1.7.3.4...v1.9.11)

Signed-off-by: dependabot[bot] <support@github.com>

Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>

* Pulled In Upstream Changes and Resolved Conflicts, Files Moved To New Folder Structure

* Merge branch 'master' into smart-flag-enum

* adding System.Text.Json converters for SmartFlagEnum

Co-authored-by: Steve Smith <steve@kentsmiths.com>
Co-authored-by: AFMHorizon <52022448+AFM-Horizon@users.noreply.github.com>
Co-authored-by: Suhaib <suhaibhasan@gmail.com>
Co-authored-by: Daniel Meza <daniel.meza2011@gmail.com>
Co-authored-by: Daniel Meza <dmeza@speedsol.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>